# Generated by Django 4.2.10 on 2024-04-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
        migrations.RenameModel(
            old_name='Workout_Types',
            new_name='Workout_Type',
        ),
    ]
