# Generated by Django 4.2.10 on 2024-04-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_plans_plan_rename_workouts_workout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_time',
            new_name='workout_days',
        ),
    ]
