# Generated by Django 4.2.10 on 2024-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_working_alter_workout_workout_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
