# Generated by Django 4.2.10 on 2024-04-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_exercise_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='fuffilment',
            field=models.PositiveIntegerField(blank=True, default=False),
        ),
    ]
