# Generated by Django 4.2.10 on 2024-04-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_exercise_fuffilment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='fuffilment',
            field=models.FloatField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_length',
            field=models.FloatField(blank=True, help_text='Duration of the workout in minutes', null=True),
        ),
    ]
