# Generated by Django 4.2.10 on 2024-04-02 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
