# Generated by Django 5.0.2 on 2024-04-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_first_login'),
        ('users', '0010_customuser_pending_friend_requests'),
    ]

    operations = [
    ]
